export enum StatutIncident {
    EN_ATTENTE = 'EN_ATTENTE',
    PRISE_EN_CHARGE = 'PRISE_EN_CHARGE',
    EN_COURS_TRAITEMENT = 'EN_COURS_TRAITEMENT',
    EN_ATTENTE_PIECE = 'EN_ATTENTE_PIECE',
    RESOLU = 'RESOLU',
    ANNULE = 'ANNULE',
    ESCALADE = 'ESCALADE',
}
